### ISSUE TITLE
Chinese  Simplified / Traditional always return absent for get-targetresource at SPInstallLanguagePack

### ISSUE THREAD

**Issue by xenophobentx** [dsccommunity/SharePointDsc#1143]
In the switch statement we might have incorrect strings, where we are matching the registry parsed products with the binary that the resource tries to check.

The reg product info returning the following strings:

$englishProducts:
Arabic
German
Spanish
French
Japanese
Korean
Portuguese (Brasil)
Russian
Thai
**Chinese (Simplified)
Chinese (Traditional** 

For SharePoint 2019 the LP binaries on server 2016 returns the following strings through the $cultureInfo object:

**Chinese (Simplified, China)
Chinese (Traditional, Taiwan)**

but in the source code we have the following switch case:

        "Chinese (Simplified, China)"
        { $languageEnglish = "Chinese (PRC)"
        }
        "Chinese (Traditional, Taiwan)"
        { $languageEnglish = "Chinese (Taiwan)"

for me the following values do the correct matching

switch ($cultureInfo.EnglishName)
    {
        "Dari (Afghanistan)" { $languageEnglish = "Dari" }
        **"Chinese (Simplified, China)" { $languageEnglish = "Chinese (Simplified)" }
        "Chinese (Traditional, Taiwan)" { $languageEnglish = "Chinese (Traditional)" }**
        "Portuguese (Brazil)" { $languageEnglish = "Portuguese (Brasil)" }
        "Portuguese (Portugal)" { $languageEnglish = "Portuguese (Portugal)" }
        "Serbian (Cyrillic, Serbia)" { $languageEnglish = "Serbian (Cyrillic)" }
        "Serbian (Latin, Serbia)" { $languageEnglish = "Serbian (Latin)" }
        "Norwegian BokmÃ¥l (Norway)" { $languageEnglish = "Norwegian" }

**Comment by ykuijs** [comment]
Hi @xenophobentx, just tested both language packs and the code runs just fine. Which version of SharePointDsc are you using?

What is the output of the following script:
```PowerShell
$registryLocation = Get-ChildItem -Path "HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall"
    $sharePointPrograms = $registryLocation | Where-Object -FilterScript {
        $_.PsPath -like "*\Office*"
    } | ForEach-Object -Process {
        Get-ItemProperty -Path $_.PsPath
    }

$sharePointPrograms.DisplayName
```

**Comment by xenophobentx** [comment]
Hello @ykuijs  we can reproduce with booth 3.4, 3.5, 3,7

Please find the output below: 

Language Pack for SharePoint and Project Server 2019 - Arabic العربية
Language Pack for SharePoint and Project Server 2019 - German/Deutsch
Language Pack for SharePoint and Project Server 2019 - Spanish/Español
Language Pack for SharePoint and Project Server 2019 - French/Français
Language Pack for SharePoint and Project Server 2019 - Japanese/日本語
Language Pack for SharePoint and Project Server 2019 - Korean/한국어
Language Pack for SharePoint and Project Server 2019 - Portuguese/Português (Brasil
Language Pack for SharePoint and Project Server 2019 - Russian/русский
Language Pack for SharePoint 2019 - Thai/ไทย
Language Pack for SharePoint and Project Server 2019 - Chinese (Simplified)/中文(简体)
Language Pack for SharePoint and Project Server 2019 - Chinese (Traditional)/中文(繁體)


Let me know if you need anything else!

**Comment by ykuijs** [comment]
I had some more time troubleshooting this issue. As it turns out there has been a change between the SP2016 and SP2019 language packs: In SP2019, the language packs were called
Language Pack for SharePoint and Project Server 2016  - Chinese (PRC)/中文(简体)
Language Pack for SharePoint and Project Server 2016  - Chinese (Taiwan)/中文 (繁體)

Apparently in SP2019, they are named:
Language Pack for SharePoint and Project Server 2019 - Chinese (Simplified)/中文(简体)
Language Pack for SharePoint and Project Server 2019 - Chinese (Traditional)/中文(繁體)

Will implement a fix asap.

**Comment by ykuijs** [comment]
@xenophobentx Quick question: I just got a report of another customer that experienced an issue after this fix, the exact reverse of what you were having.

As it turns out their Chinese SP2019 Language Pack on their environment was still called "Chinese (PRC)" as opposed to your situation. So I downloaded the Chinese language pack myself and installed it on my test environment. There it was also called "Chinese (PRC)".

So now I am wonder how it is possible that on your environment it is named differently. Where did you get the package from? Do you have clue how this is possible?
