### ISSUE TITLE
MSFT_SPContentDatabase: Checking existing database always throw exception

### ISSUE THREAD

**Issue by VerdonTrigance** [dsccommunity/SharePointDsc#1157]
#### Details of the scenario you tried and the problem that is occurring

Repo step:
1. Create new content database passing only name and webapplication
2. Ensure database is created
3. Run same script again
4. Get exception:
`Specified database server does not match the actual database server. This resource cannot move the database to a different SQL instance.`

#### Verbose logs showing the problem

```
Set-ContentDatabase -Name $ContentDatabaseName -WebAppUrl $WebApplication -Ensure Present -Debug
VERBOSE: Executing as the local run as user user
VERBOSE: Leaving BeginProcessing Method of Get-SPDatabase.
VERBOSE: Leaving ProcessRecord Method of Get-SPDatabase.
VERBOSE: Leaving EndProcessing Method of Get-SPDatabase.
VERBOSE: Leaving BeginProcessing Method of Get-SPWebApplication.
VERBOSE: Leaving ProcessRecord Method of Get-SPWebApplication.
VERBOSE: Leaving EndProcessing Method of Get-SPWebApplication.
Specified database server does not match the actual database server. This resource cannot move the database to a different SQL instance.
At line:32 char:21
+ ...             throw ("Specified database server does not match the actu ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Specified datab...t SQL instance.:String) [], RuntimeException
    + FullyQualifiedErrorId : Specified database server does not match the actual database server. This resource cannot move the database to a different SQL instance.
```
Here Set-ContentDatabase is Set-TargetResource. I just call it explicitly from resource file.

#### Suggested solution to the issue
```
if ($cdb.Server -ne $params.DatabaseServer)
                {
                    throw ("Specified database server does not match the actual database " + `
                            "server. This resource cannot move the database to a different " + `
                            "SQL instance.")
                }
```
This validation is always throw exception if I do not pass DatabaseServer param to resource (and I really don't wanna pass it).

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)

```powershell
# insert configuration here
```

**Comment by ruandersMSFT** [comment]
@VerdonTrigance The code is comparing the existing Database Server value against an empty value since you are not passing that value; thus, it determines that the database server does not match.  You should ensure you are using the _DatabaseServer_ parameter as part of _SPContentDatabase_ so that comparison of desired state vs current state can be determined as matching.

**Comment by VerdonTrigance** [comment]
@ruandersMSFT This behavior is illogical. As I mentioned before same script should be idempotent, but we have opposite situation! 
Script should check state of database with given name in current server if parameter has not been passed explicitly.
Current situation can not be called idempotent what ruins core DSC principles.

**Comment by ruandersMSFT** [comment]
Perhaps @ykuijs can weight in.  Based on the design intent of the SPContentDatabase Module, the DatabaseServer parameter is required given the value comparison to check for condition in which attempt to move a database is occurring (raising error that this operation is not supported by the module).  Given this previous design intent of the module, the parameter must be supplied for validation.

**Comment by ykuijs** [comment]
We should not make the database server parameter mandatory, because of the fact that if you don't specify a database parameter in New-SPContentDatabase, the database is automatically created on the default database server.

On the other side, we also should not check against the default database server, because it is possible that the default database server is changed after creating the database. Automatically checking against the default database server would mean the resource is no longer in compliance.

The only good option in my opinion is to ignore the database server parameter if it is not supplied. So something like:
```PowerShell
if ($params.ContainsKey('DatabaseServer') -and $cdb.Server -ne $params.DatabaseServer)
```

@ruandersMSFT Since this this update isn't a breaking change, we do not have to target that to v4.0. Could you create a new PR based on the master branch, which adds this check?

**Comment by ruandersMSFT** [comment]
Tested and verified with both creating on new SPContentDatabase and re-run against an existing SPContentDatabase.

**Comment by ykuijs** [comment]
@ruandersMSFT Did you submit a PR with this change already? I cannot find it anywhere

**Comment by ruandersMSFT** [comment]
@ykuijs Not yet.  Code change done, was going to look to add a test or two.  When are you planning to release v3.8?

**Comment by ykuijs** [comment]
As soon as possible. I would like to merge all current PRs and implement one more update to the new CI system. Hopefully later this week/early next week.
