### ISSUE TITLE
SPAppCatalog resource should not depend on CredSSP

### ISSUE THREAD

**Issue by pessimism** [dsccommunity/SharePointDsc#1198]
## Details of the scenario you tried and the problem that is occurring
-Use SPAppCatalog resource to set App Catalog site in an environment without CredSSP, using the farm administrator account as PsDscRunAsCredential

-Resource fails as it is coded to force the user to use a non-farm admin account which then retrieves the farm account but requires CredSSP.  This behaviour is contrary to every other SharePointDSC resource I have used to build the farm.

#### Suggested solution to the issue
Use logic that does not require CredSSP.  Enabling CredSSP has security implications and is forbidden in many corporate environments.  You could simply require a parameter named "FarmAdministratorCredential" or not attempt to use CredSSP if the runascredential provided is the farm account.

#### Version of SharePoint that is used (e.g. SharePoint 2016)
2019

#### Version and build of PowerShell the target node is running
5.1

#### Version of the DSC module that was used
3.7.0.0

**Comment by ykuijs** [comment]
In the past that was the way the resource operated, but this meant that the Farm account required local administrative permissions in order to run successfully. Without these permissions the farm account would get Access Denied errors. And since granting the Farm account is against various security best practices, we decided to change this behavior. 

Right now we retrieve the farm account, temporarily grant this account local admin permissions, run the code as the farm account and then remove the permissions again. The only downside is that this method requires CredSSP to be configured.

This same behavior is also implemented in SPUserProfileSyncService.

**Comment by ykuijs** [comment]
Another comment: You suggestion to add a FarmAdministratorCredential parameter will also require CredSSP to be configured.

The only way to prevent the use of CredSSP is to use the Farm account as PsDscRunAsCredential, but that method requires that the farm account has local admin privileges at all times. That is also an issue in most corporate environments.

So in short: I would love to remove the requirement for CredSSP, but at the moment we have no possibility to do so without introducing other security issues. If you have any great idea, please let us know.

Closing the issue for now.
