### ISSUE TITLE
IsPaused Property of the SPSearchServiceApp

### ISSUE THREAD

**Issue by shurick81** [dsccommunity/SharePointDsc#1232]
### Description

Would not it be great to have a separate resource or a property of the SPSearchServiceApp resource that allows controlling the IsPaused property of the search service application?

### Proposed properties

IsPaused, boolean property.

**Comment by ykuijs** [comment]
There are many reasons why a search service application would be paused:
https://docs.microsoft.com/en-us/sharepoint/search/manage-a-paused-search-service-application
Only when the SSA has been paused manually is it a good idea to resume manually. In all other cases, SharePoint has a reason to pause the SSA.

I am a bit in doubt is DSC is a good place to manage the state of this setting. Usually this setting is only used in case of specific maintenance and only temporary. Using DSC for this sounds a bit overkill: Update your config, deploy the config, do your maintenance, update the config again and then redeploy this updated config.

@NikCharlebois What do you think?

**Comment by NikCharlebois** [comment]
As @ykuijs mentioned, I wouldn't recommend managing 'stateful' config using DSC. In an ideal situation, you would have something like this:

SPSearchServiceApp Before
{
      IsPaused = $true
}
SP[Whatever to do the upgrade]
{
   ...
}
SPSearchServiceApp After
{
    IsPaused = $false
}

The problem with this is that if your consistency check is done while you are not trying to do an update, the Test-TargetResource method will always return $false on the "Before" instance because it will never be paused (or rather it can't be both Paused and 'not-paused' at the same time. 

A DSC config defines an end-state picture of how the environment should be, not a sequence of action to be performed on the state of an environment. We are facing the same issue when we build an SP VM from scratch, where we start off by downloading the ISO file from the web locally, then install SharePoint from it. There is no way after this for us to delete the downloaded files for cleaning up the VM once we no longer need them. Imaging the following sequence of DSC resources:

[Download ISO and copy files locally]
[Install SharePoint]
[Delete the local Files]

This will work fine on the first run. However, the consistency check 15 minutes later will get to the Download ISO stage, figure out that the files are not downloaded, and re-download them all. Then the install step will simply be skipped because SP is already installed, and then the file will be deleted, only for this whole dance to be repeated again in 15 minutes. 

Let me know if my ranting above makes sense? Bottom line is, I wouldn't recommend doing it :)

**Comment by shurick81** [comment]
I did not know that SA can be paused automatically for some reasons so what we want to handle is probably manual "start". However, I don't really see the contradition to the fact that DSC config defines an end state picture. In my definition of end state this service application should be up and running fully, so it should be "unpaused". That is the desired state. I totally get the example regarding downloading and deleting files, and I am familiar with this mistake, yes. But I'm not sure that this particular property corresponds to this pattern. Maybe you are right, so let's skip it for now :)

**Comment by ykuijs** [comment]
> my definition of end state this service application should be up and running fully, so it should be "unpaused"

Not necessarily. Why would the end state always be that the service application would be fully running? I can imagine there are specific situations that the desired end state would be: "A Search SA that is in a Paused state". For example when you are performing a migration and don't want to delete the SSA just yet, but don't want it running as well.

And what if the SA has been paused for a technical reason. Just trying to start the SA without checking why it is paused might cause issues.

For now I would say we do not implement this suggestion.
