### ISSUE TITLE
The specified RequiredModules entry 'ReverseDSC' in the module manifest

### ISSUE THREAD

**Issue by IlleNilsson** [dsccommunity/SharePointDsc#1295]
ISSUE TITLE:
 I'm downloading the 4.5.1 SharePointDsc module, to a local detonation repo, then to a local repo available for internal nodes (computers)
    ISSUE DESCRIPTION (this template):
Then i get this: The specified RequiredModules entry 'ReverseDSC' in the module manifest

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

**Comment by ykuijs** [comment]
Hi @IlleNilsson, you are correct: With the release of v4.5/v4.5.1, the ReverseDsc module is required, since we have added native ReverseDsc support to SharePointDsc.

However, since this is only required when actually doing an export, I have changed this requirement to specifically check for the existence of the module when running an export. So with the release of v4.6, ReverseDsc is no longer required for deploying configurations.

Please add the ReverseDsc module to your repo as well or wait for v4.6.

**Comment by IlleNilsson** [comment]
Thanks

________________________________
