### ISSUE TITLE
Add SPSearchCrawlStore resource

### ISSUE THREAD

**Issue by typozh** [dsccommunity/SharePointDsc#493]
**Details of the scenario you try and problem that is occurring:**
For a large search topology I'm missing a few things. One is that all the databases are created in the same sql instance. The name cannot be configured individually and there is only one property for the sql server. And I need to create multiple crawl store databases which is not possible with the current version. The multiple crawl databases are also the reason why it would be nice to name the first crawl store db ...crawlstore01.
Could this be implemented simular to the index partitions with an additional resource like SPSearchCrawlStore to create additional crawl dbs? 

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Windows 2012, PS5

**Version of the DSC module you're using:**
1.5.0.0

**Comment by ykuijs** [comment]
Hi @typozh, we have tried this in the past, but this is because of a limitation in SharePoint Powershell: The New-SPEnterpriseSearchServiceApplication cmdlet only accepts one database parameter (https://technet.microsoft.com/en-us/library/ff607751.aspx).

This means that if you want to move the databases to different instance, you need to use backup/restore in order to move the databases (https://technet.microsoft.com/en-us/library/jj729803.aspx). This is too complex to script as part of SharePointDsc.

For the crawl store suggestion: @BrianFarnhill what is your opinion on this?

**Comment by BrianFarnhill** [comment]
So the request to move search DBs has been in the backlog for a while as #345 - we just haven't implemented it due to time and the complexities that @ykuijs mentioned there. It's something I wouldn't mind getting in there but we haven't been able to get it sorted yet. When we look at this we'll also then be able to look at renaming databases as well, but there are some data protection controls I want to see us put in there first to be sure that we will never lose customer data through any changes here.

As for the crawl store suggestion, I would need to look up the PowerShell cmdlets for it to make sure its feasible to put it in as a DSC resource for additional crawl stores, but in principal I'm comfortable with putting this in.

**Comment by ykuijs** [comment]
The cmdlets needed for this resource would be:

- [New-SPEnterpriseCrawlDatabase](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/new-spenterprisesearchcrawldatabase)
- [Get-SPEnterpriseCrawlDatabase](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/get-spenterprisesearchcrawldatabase)
- [Set-SPEnterpriseCrawlDatabase](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/set-spenterprisesearchcrawldatabase)
- [Remove-SPEnterpriseCrawlDatabase](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/remove-spenterprisesearchcrawldatabase)

**Comment by ykuijs** [comment]
Received a customer request for this resource. Working on creating it!
