### ISSUE TITLE
Search Index Deletion Policies Resource

### ISSUE THREAD

**Issue by typozh** [dsccommunity/SharePointDsc#494]
**Details of the scenario you try and problem that is occurring:**
It would be great to have a resource to configure the search index deletion policies to configure the behaviour of item deletion from the index. The PowerShell commands are described here: https://technet.microsoft.com/en-us/library/hh127009(v=office.14).aspx (could not find a 2013/16 article but the commands are the same, default values have changed)
http://geekswithblogs.net/simonh/archive/2013/12/09/search-crawl-deletion-policies-sharepoint-2013.aspx
Maybe the properties could be added to the SPSearchServiceApp resource because as these are just settings for the search service app.

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Windows 2012, PS5

**Version of the DSC module you're using:**
1.5.0.0

**Comment by BrianFarnhill** [comment]
@typozh From a quick glance at the articles you have there, I think the solution here would be to put these properties on to the existing SPSearchServiceApp resource. I'll tag this as enhancements and we can get it looked at from there.

**Comment by typozh** [comment]
Any news on this one?

**Comment by BrianFarnhill** [comment]
@typozh Unfortunately not - all the contributions to this module come from guys who are doing it on their own time, not something that we get given time to do things on. I know if I get some time I would like to get this one in as well, but just haven't had the time unfortunately.

**Comment by typozh** [comment]
Hi Brian,
I appreciate your work and I fully understand. We use your resource for our SharePoint 2016 farm which is one of the largest environments in Switzerland. It helped a lot to automate the setup and configuration and to maintain it. 
Do you have any guides on how to participate in the project? I might be able to write it myself and contribute to the project. Depends on the amount of overhead compared to writing it just for my company.
Thanks again for the good work!

**Comment by ykuijs** [comment]
@typozh, we can always use help. No matter how big or small the contribution is!

Our Wiki contains an article on how to contribute: https://github.com/PowerShell/SharePointDsc/wiki/Contributing%20to%20SharePointDsc

This article however doesn't say much about the technical aspect. To start, you have to create your own fork by clicking the Fork button at the top of the page. You can then sync your own fork to your local machine using the Github Desktop.

Once it is synced, you can start making changes to the resource. Please make sure you test all changes against SP2013 and SP2016. And since we use Pester to perform unit tests, it is required to create Pester tests as well.

When you are done, you can create a Pull Request from your own fork to our repository. We will review the changes and merge them if they are good enough.

More information about using Git: https://git-scm.com/book/en/v2
More information about how to create DSC resources: https://mva.microsoft.com/en-US/training-courses/advanced-powershell-desired-state-configuration-dsc-and-custom-resources-8702

**Comment by ronx** [comment]
Also some good info here:

https://github.com/PowerShell/DscResources/blob/master/CONTRIBUTING.md#fixing-an-issue

**Comment by ykuijs** [comment]
Great, thanks @ronx! Will add this link to our Wiki page.

**Comment by ronx** [comment]
@ykuijs I had started compiling a new "how to contribute" page but haven't had a chance to work on it much lately. Maybe you can help check the content here: 

https://github.com/ronx/SharePointDsc/wiki/Contributing-to-SharePointDsc

**Comment by ykuijs** [comment]
Will do!

**Comment by ykuijs** [comment]
Closed via #1361
